# Generated by Django 2.2.9 on 2020-04-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20200412_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
